# Woodpecker CI pipeline for DeployNet
# Free CI/CD using Codeberg's Woodpecker

pipeline:
  build-go:
    image: golang:1.21
    commands:
      - cd cmd/signaling-server
      - go mod tidy
      - go build -o deploynet-signaling .
    when:
      event: [push, pull_request, tag]

  build-js:
    image: node:18
    commands:
      - npm install
      - npm run build
    when:
      event: [push, pull_request, tag]

  test:
    image: node:18
    commands:
      - npm install
      - npm test
    when:
      event: [push, pull_request]

  lint:
    image: node:18
    commands:
      - npm install
      - npm run lint
    when:
      event: [push, pull_request]

services:
  redis:
    image: redis:7-alpine

branches:
  include:
    - main
    - develop
    - feature/*
    - hotfix/*

clone:
  depth: 1